# docker-compose.yml
version: '3.1'

services:

  consignment-cli:
    build: ./consignment-cli
    environment:
      MICRO_REGISTRY: "mdns"

  consignment-service:
      build: ./consignment-service
      ports:
        - 50051:50051
      environment:
        MICRO_SERVER_ADDRESS: ":50051"
        MICRO_REGISTRY: "mdns"
        DB_HOST: "datastore:27001"

  vessel-service:
      build: ./vessel-service
      ports:
        - 50052:50051
      environment:
        MICRO_SERVER_ADDRESS: ":50051"
        MICRO_REGISTRY: "mdns"
